package invoicing.view;

public enum MenuCommand {
	NONE, EXIT, LOAD, SAVE,
	ADD_PRODUCT, LIST_ALL_PRODUCTS,
	ADD_CONTRAGENT, LIST_ALL_CONTRAGENTS,
	SET_ISSUER, 
	ADD_INVOICE, PRINT_LAST_INVOICE, PRINT_LAST_INVOICE_TO_FILE, 
	LIST_ALL_INVOICES, GENERATE_INVOICING_REPORT_AS_CSV_FILE	
}
